name: versus
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+7

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  rxdart: ^0.27.7
  toast: ^0.3.0
  shared_preferences: ^2.2.2
  lottie: ^2.3.2
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  provider: ^6.1.1
  #package_info_plus: ^4.2.0
  flutter_masked_text2: ^0.9.1
  intl: ^0.18.1
  after_layout: ^1.2.0
  currency_text_input_formatter: ^2.1.10
  number_pagination: ^0.0.3+2
  floating_action_bubble: ^1.1.4
  syncfusion_flutter_datepicker: ^22.2.12
  image_picker: ^1.0.4
  characters: ^1.2.1
  url_launcher: ^6.1.11
  file_picker: ^5.3.1
  shorebird_code_push: ^1.1.3
  collection: ^1.15.0-nullsafety.4
  badges: ^3.1.2
  restart_app: ^1.2.1
  flutter_linkify: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - shorebird.yaml
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Saira
      fonts:
        - asset: fonts/SairaSemiCondensed-Thin.ttf
          weight: 100
        - asset: fonts/SairaSemiCondensed-ExtraLight.ttf
          weight: 200
        - asset: fonts/SairaSemiCondensed-Light.ttf
          weight: 300
        - asset: fonts/SairaSemiCondensed-Regular.ttf
          weight: 400
        - asset: fonts/SairaSemiCondensed-Medium.ttf
          weight: 500
        - asset: fonts/SairaSemiCondensed-SemiBold.ttf
          weight: 600
        - asset: fonts/SairaSemiCondensed-Bold.ttf
          weight: 700
        - asset: fonts/SairaSemiCondensed-ExtraBold.ttf
          weight: 800
        - asset: fonts/SairaSemiCondensed-Black.ttf
          weight: 900
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
